title: raularenas.com
author: Raul Arenas
email: hello@raularenas.com
url: https://raularenas.com
description: >
  Designing products that feel natural and last.

permalink: /:slug.html  # or change to /:slug/ if you prefer folder-style URLs

favicon: "./favicon.ico"   # relative path to site's favicon

# Pagination (must be top-level)
paginate: 2
paginate_path: "page:num"

# Analytics
goat_counter: rulan


theme_config:
  appearance: "light"         # light/dark/auto
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: true



sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
